#include "VulkanWater.h"
#include "VulkanCore/VkDescriptors.h"
#include "VulkanCore/VulkanRenderPass.h"
#include "VulkanCore/VulkanTexture.h"
#include "VulkanCore/VulkanEngine.h"
#include "VulkanCore/VulkanDeferred.h"
#include "VulkanCore/TerrainUtility.h"
#include "VulkanCore/VulkanTexture.h"
#include "VulkanCore/vulkan_shadow.h"
#include "VulkanCore/vkFFT.h"
#include "Systems/camera_system.h"
#include "Engine/world.h"
#include "Engine/engine.h"


VulkanWater::VulkanWater(VulkanEngine *engine, MemoryAllocator *memory) :
	VulkanModule(memory),
	p_vkEngine(engine)
{
	p_FFT = new vkFFT(p_vkEngine, p_vkMemory);

	// setup default water parameters - TODO : this will be set when the world is generated by data stored in .json config file
	m_waterParams.amplitude = 60.0f;
	m_waterParams.time = 0.8f;
	m_waterParams.choppiness = 1.3f;
	m_waterParams.windDir = glm::vec2(0.6f, 0.8f);
	m_waterParams.windSpeed = 100.0f;
	m_waterParams.patchLength = 1000.0f;

	Init();
}


VulkanWater::~VulkanWater()
{
	Destroy();
}

void VulkanWater::PrepareBuffers()
{
	// evaluation tesselation ubo
	m_waterInfo.uboTese = p_vkMemory->AllocateSegment(MemoryUsage::VK_BUFFER_DYNAMIC, sizeof(TerrainTeseUbo));
	
	// fragment shader ubo
	m_waterInfo.uboFrag = p_vkMemory->AllocateSegment(MemoryUsage::VK_BUFFER_DYNAMIC, sizeof(TerrainFragUbo));
}

void VulkanWater::PrepareDescriptorSets()
{
	m_waterInfo.descriptors = new VkDescriptors(p_vkEngine->GetDevice());

	std::vector<VkDescriptors::LayoutBinding> layoutBinding =
	{
		{ VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT | VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT },						// bindings for the UBO	
		{ VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT | VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT },				// bindings for the displacement map image sampler
		{ VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, VK_SHADER_STAGE_FRAGMENT_BIT },																		// normal map
		{ VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, VK_SHADER_STAGE_FRAGMENT_BIT | VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT },							// bindings for perlin noise texture
		{ VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, VK_SHADER_STAGE_FRAGMENT_BIT }
	};
	m_waterInfo.descriptors->AddDescriptorBindings(layoutBinding);

	std::vector<VkDescriptorBufferInfo> bufferInfo =
	{
		{ p_vkMemory->blockBuffer(m_waterInfo.uboTese.block_id), m_waterInfo.uboTese.offset, m_waterInfo.uboTese.size },
		{ p_vkMemory->blockBuffer(m_waterInfo.uboFrag.block_id), m_waterInfo.uboFrag.offset, m_waterInfo.uboFrag.size }
	};
	std::vector<VkDescriptorImageInfo> imageInfo =
	{
		{ p_FFT->m_images.displacement->texSampler, p_FFT->m_images.displacement->imageView, vk::ImageLayout::eShaderReadOnlyOptimal },		// displacement texture sampler - derives from compute shader computations
		{ p_FFT->m_images.normal->texSampler, p_FFT->m_images.normal->imageView, vk::ImageLayout::eShaderReadOnlyOptimal },					// texture sampler for normal map
		{ m_waterInfo.noiseImage->texSampler, m_waterInfo.noiseImage->imageView, vk::ImageLayout::eShaderReadOnlyOptimal }					// texture sampler for perlin noise
	};

	m_waterInfo.descriptors->GenerateDescriptorSets(bufferInfo.data(), imageInfo.data());
}

void VulkanWater::PreparePipeline()
{
	auto vkDeferred = p_vkEngine->VkModule<VulkanDeferred>();

	// tesselation pipeline
	TerrainUtility::Vertex vertex;
	auto bindingDescr = vertex.GetInputBindingDescription();
	auto attrDescr = vertex.GetAttrBindingDescription();

	VkPipelineVertexInputStateCreateInfo vertexInfo = {};
	vertexInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
	vertexInfo.vertexBindingDescriptionCount = 1;
	vertexInfo.pVertexBindingDescriptions = &bindingDescr;
	vertexInfo.vertexAttributeDescriptionCount = static_cast<uint32_t>(attrDescr.size());
	vertexInfo.pVertexAttributeDescriptions = attrDescr.data();

	VkPipelineInputAssemblyStateCreateInfo assemblyInfo = {};
	assemblyInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
	assemblyInfo.topology = VK_PRIMITIVE_TOPOLOGY_PATCH_LIST;										// used for tesselation shader draw
	assemblyInfo.primitiveRestartEnable = VK_FALSE;

	VkPipelineViewportStateCreateInfo viewportState = VulkanUtility::InitViewPortCreateInfo(p_vkEngine->GetViewPort(), p_vkEngine->GetScissor(), 1, 1);

	VkPipelineRasterizationStateCreateInfo rasterInfo = VulkanUtility::InitRasterzationState(VK_POLYGON_MODE_FILL, VK_CULL_MODE_NONE, VK_FRONT_FACE_COUNTER_CLOCKWISE);

	VkPipelineMultisampleStateCreateInfo multiInfo = VulkanUtility::InitMultisampleState(VK_SAMPLE_COUNT_1_BIT);

	// colour attachment required for each colour buffer
	std::array<VkPipelineColorBlendAttachmentState, 8> colorAttach = {};
	colorAttach[0].colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
	colorAttach[0].blendEnable = VK_FALSE;
	colorAttach[1].colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
	colorAttach[1].blendEnable = VK_FALSE;
	colorAttach[2].colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
	colorAttach[2].blendEnable = VK_FALSE;
	colorAttach[3].colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
	colorAttach[3].blendEnable = VK_FALSE;
	colorAttach[4].colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
	colorAttach[4].blendEnable = VK_FALSE;
	colorAttach[5].colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
	colorAttach[5].blendEnable = VK_FALSE;
	colorAttach[6].colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
	colorAttach[6].blendEnable = VK_FALSE;
	colorAttach[7].colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
	colorAttach[7].blendEnable = VK_FALSE;

	VkPipelineColorBlendStateCreateInfo colorInfo = {};
	colorInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
	colorInfo.logicOpEnable = VK_FALSE;
	colorInfo.attachmentCount = static_cast<uint32_t>(colorAttach.size());
	colorInfo.pAttachments = colorAttach.data();

	VkDynamicState states[] = { VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR, VK_DYNAMIC_STATE_LINE_WIDTH };
	VkPipelineDynamicStateCreateInfo dynamicInfo = {};
	dynamicInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
	dynamicInfo.pDynamicStates = states;
	dynamicInfo.dynamicStateCount = 3;

	VkPipelineDepthStencilStateCreateInfo depthInfo = {};
	depthInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
	depthInfo.depthTestEnable = VK_TRUE;
	depthInfo.depthWriteEnable = VK_TRUE;
	depthInfo.depthCompareOp = VK_COMPARE_OP_LESS_OR_EQUAL;

	// enable stencil test - to ensure that the skybox is rendered correctly
	depthInfo.stencilTestEnable = VK_TRUE;
	depthInfo.back.compareOp = VK_COMPARE_OP_ALWAYS;
	depthInfo.back.failOp = VK_STENCIL_OP_REPLACE;
	depthInfo.back.depthFailOp = VK_STENCIL_OP_REPLACE;
	depthInfo.back.passOp = VK_STENCIL_OP_REPLACE;
	depthInfo.back.writeMask = 0xff;
	depthInfo.back.compareMask = 0xff;
	depthInfo.back.reference = 1;
	depthInfo.front = depthInfo.back;

	VkPipelineTessellationStateCreateInfo tessInfo = {};
	tessInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO;
	tessInfo.patchControlPoints = 4;		//	patch quad

	VkPipelineLayoutCreateInfo pipelineInfo = {};
	pipelineInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
	pipelineInfo.setLayoutCount = 1;
	pipelineInfo.pSetLayouts = &m_waterInfo.descriptors->layout;
	pipelineInfo.pPushConstantRanges = 0;
	pipelineInfo.pushConstantRangeCount = 0;

	VK_CHECK_RESULT(vkCreatePipelineLayout(p_vkEngine->GetDevice(), &pipelineInfo, nullptr, &m_waterInfo.pipelineInfo.layout));

	// load the shaders with tyexture samplers for material textures
	m_waterInfo.shader[0] = VulkanUtility::InitShaders("terrain/water/water-vert.spv", VK_SHADER_STAGE_VERTEX_BIT, p_vkEngine->GetDevice());
	m_waterInfo.shader[1] = VulkanUtility::InitShaders("terrain/water/water-frag.spv", VK_SHADER_STAGE_FRAGMENT_BIT, p_vkEngine->GetDevice());
	m_waterInfo.shader[2] = VulkanUtility::InitShaders("terrain/water/water-tesc.spv", VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT, p_vkEngine->GetDevice());
	m_waterInfo.shader[3] = VulkanUtility::InitShaders("terrain/water/water-tese.spv", VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT, p_vkEngine->GetDevice());

	VkGraphicsPipelineCreateInfo createInfo = {};
	createInfo.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
	createInfo.stageCount = static_cast<uint32_t>(m_waterInfo.shader.size());
	createInfo.pStages = m_waterInfo.shader.data();
	createInfo.pVertexInputState = &vertexInfo;
	createInfo.pInputAssemblyState = &assemblyInfo;
	createInfo.pViewportState = &viewportState;
	createInfo.pRasterizationState = &rasterInfo;
	createInfo.pMultisampleState = &multiInfo;
	createInfo.pDepthStencilState = &depthInfo;
	createInfo.pColorBlendState = &colorInfo;
	createInfo.pDynamicState = &dynamicInfo;
	createInfo.pTessellationState = &tessInfo;
	createInfo.layout = m_waterInfo.pipelineInfo.layout;
	createInfo.renderPass = vkDeferred->GetRenderPass();			// render into the offscreen buffer
	createInfo.subpass = 0;											// G buffer pass
	createInfo.basePipelineIndex = -1;
	createInfo.flags = VK_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT;
	createInfo.basePipelineHandle = VK_NULL_HANDLE;

	VK_CHECK_RESULT(vkCreateGraphicsPipelines(p_vkEngine->GetDevice(), VK_NULL_HANDLE, 1, &createInfo, nullptr, &m_waterInfo.pipelineInfo.pipeline));

	// wireframe draw pipeline
	rasterInfo.polygonMode = VK_POLYGON_MODE_LINE;
	VK_CHECK_RESULT(vkCreateGraphicsPipelines(p_vkEngine->GetDevice(), VK_NULL_HANDLE, 1, &createInfo, nullptr, &m_waterInfo.wirePipeline));
}

void VulkanWater::GenerateWaterCmdBuffer(VkCommandBuffer cmdBuffer, bool drawShadow)
{
	VkDeviceSize bgOffsets[] = { m_waterInfo.vertices.offset };

	if (!drawShadow) {
		vkCmdSetLineWidth(cmdBuffer, 1.0f);
		vkCmdBindPipeline(cmdBuffer, vk::PipelineBindPoint::eGraphics, (p_vkEngine->drawWireframe()) ? m_waterInfo.wirePipeline : m_waterInfo.pipelineInfo.pipeline);
		vkCmdBindDescriptorSets(cmdBuffer, vk::PipelineBindPoint::eGraphics, m_waterInfo.pipelineInfo.layout, 0, 1, &m_waterInfo.descriptors->set, 0, NULL);
	}
	else {
		auto shadow = p_vkEngine->VkModule<VulkanShadow>();

		// try and reduce artifacts
		vkCmdSetDepthBias(cmdBuffer, VulkanShadow::biasConstant, 0.0f, VulkanShadow::biasSlope);

		vkCmdBindPipeline(cmdBuffer, vk::PipelineBindPoint::eGraphics, shadow->GetPipeline());		// use shadow pipeline for draw
		vkCmdBindDescriptorSets(cmdBuffer, vk::PipelineBindPoint::eGraphics, shadow->GetPipelineLayout(), 0, 1, &shadow->GetDescriptorSet(), 0, NULL);

		VulkanShadow::PushConstant push;
		push.useModelIndex = 0;					// inform the shadow shader to add the model transform to the light matrix	
		vkCmdPushConstants(cmdBuffer, shadow->GetPipelineLayout(), VK_SHADER_STAGE_VERTEX_BIT, 0, sizeof(VulkanShadow::PushConstant), &push);

	}

	vkCmdBindVertexBuffers(cmdBuffer, 0, 1, &p_vkMemory->blockBuffer(m_waterInfo.vertices.block_id), bgOffsets);
	vkCmdBindIndexBuffer(cmdBuffer, p_vkMemory->blockBuffer(m_waterInfo.indices.block_id), m_waterInfo.indices.offset, VK_INDEX_TYPE_UINT32);
	vkCmdDrawIndexed(cmdBuffer, m_waterInfo.indexCount, 1, 0, 0, 0);
}

void VulkanWater::SubmitWaterCompute()
{
	// submit fft compute shaders - spectrum, FFT and displacement
	p_FFT->SubmitFFTCompute();
}

// ================================================================ mesh generation ======================================================================================
void VulkanWater::GenerateMeshData()
{
	TerrainUtility *p_utility = new TerrainUtility();

	// generate vertices and uv data
	std::vector<TerrainUtility::Vertex> vertices;
	p_utility->GenerateVertices(PATCH_SIZE, UV_SCALE, vertices);

	// generate the indices for the patch quads
	m_waterInfo.indexCount = ((PATCH_SIZE - 1) * (PATCH_SIZE - 1)) * 4;

	std::vector<uint32_t> indices;
	p_utility->GenerateIndices(PATCH_SIZE, indices);

	// now map to device memory
	// vertex
	m_waterInfo.vertices = p_vkMemory->AllocateSegment(MemoryUsage::VK_BUFFER_STATIC, vertices.size() * sizeof(TerrainUtility::Vertex));
	p_vkMemory->MapDataToSegment<TerrainUtility::Vertex>(m_waterInfo.vertices, vertices);

	//index
	m_waterInfo.indices = p_vkMemory->AllocateSegment(MemoryUsage::VK_BUFFER_STATIC, indices.size() * sizeof(uint32_t));
	p_vkMemory->MapDataToSegment<uint32_t>(m_waterInfo.indices, indices);

	delete p_utility;
}

 // =============================================================== general functions ====================================================================================

void VulkanWater::LoadWaterAssets()
{
	// import the tiling image
	m_waterInfo.noiseImage = new VulkanTexture(p_vkEngine->GetPhysicalDevice(), p_vkEngine->GetDevice());
	m_waterInfo.noiseImage->LoadTexture("assets/textures/perlin_noise.ktx", VK_SAMPLER_ADDRESS_MODE_REPEAT, 16.0f, VK_BORDER_COLOR_FLOAT_OPAQUE_WHITE, VK_FORMAT_BC3_UNORM_BLOCK, p_vkEngine->GetCmdPool(), p_vkEngine->GetGraphQueue(), p_vkMemory);
}

void VulkanWater::Update(int acc_time)
{
	auto camera = p_vkEngine->GetCurrentWorld()->RequestSystem<CameraSystem>();

	// update terrain tesselation ubo
	std::vector<TerrainTeseUbo> ubo(1);
	ubo[0].projection = camera->m_cameraInfo.projection;
	ubo[0].viewMatrix = camera->m_cameraInfo.viewMatrix;
	ubo[0].cameraPos = -glm::vec4(camera->GetCameraPosition(), 1.0f);
	ubo[0].modelMatrix = glm::mat4(1.0f);
	ubo[0].screenDim = glm::vec2(p_vkEngine->GetSurfaceExtentW(), p_vkEngine->GetSurfaceExtentH());

	// perlin noise constants
	ubo[0].perlinOctave = PERLIN_OCTAVE;
	ubo[0].perlinAmplitude = PERLIN_AMPLITUDE;
	ubo[0].perlinMovement = -m_waterParams.windDir * (float)acc_time * PERLIN_SPEED;

	// constant tessellation values
	ubo[0].dispFactor = TESSELLATION_DISP_FACTOR;		// not used - REMOVE!
	ubo[0].tessFactor = p_vkEngine->tesselationFactor();
	ubo[0].tessEdgeSize = p_vkEngine->tessEdgeSize();
	p_vkMemory->MapDataToSegment<TerrainTeseUbo>(m_waterInfo.uboTese, ubo);

	// fragment data ubo update
	std::vector<TerrainFragUbo> fragUbo(1);
	fragUbo[0].perlinOctave = PERLIN_OCTAVE;
	fragUbo[0].perlinMovement = m_waterParams.windDir * (float)acc_time * PERLIN_SPEED;		// updated per draw call
	fragUbo[0].perlinGradient = PERLIN_GRADIENT;
	fragUbo[0].texelSize2x = m_waterParams.patchLength / static_cast<float>(512 * 2);
	p_vkMemory->MapDataToSegment<TerrainFragUbo>(m_waterInfo.uboFrag, fragUbo);

	// update the local time
	app_time += acc_time;

	// update the time dependent h(t)
	p_FFT->Update(static_cast<float>(app_time), m_waterParams.patchLength);
}

void VulkanWater::Init()
{
	// set timer to zero
	app_time = 0.0;

	// Begin by importing required textures
	LoadWaterAssets();

	// The order of calculation flow is as follows:
	// 1. h0(k) and h0(-k) values are generated before compute shaders
	// 2. time dependent h0 values are generated
	// 3. the fast fourier transform is carried out using the h(t) values
	// 4. a displacement map is created - d(x,y,z)
	// 5. the gradient map is created from the displacement data
	float amplitude = p_vkEngine->waveAmplitude();
	p_FFT->Init(m_waterParams.patchLength, m_waterParams.windSpeed, amplitude, m_waterParams.windDir);

	// genertae mesh data for tessellation
	GenerateMeshData();

	// init rendering pipeline
	PrepareBuffers();
	PrepareDescriptorSets();
	PreparePipeline();
}

void VulkanWater::Destroy()
{
	vkDestroyPipeline(p_vkEngine->GetDevice(), m_waterInfo.pipelineInfo.pipeline, nullptr);
	vkDestroyPipeline(p_vkEngine->GetDevice(), m_waterInfo.wirePipeline, nullptr);
	vkDestroyPipelineLayout(p_vkEngine->GetDevice(), m_waterInfo.pipelineInfo.layout, nullptr);
	
	delete m_waterInfo.descriptors;
	delete m_waterInfo.noiseImage;

	delete p_FFT;

	p_FFT = nullptr;
	p_vkEngine = nullptr;
}

void VulkanWater::GenerateH0Map()
{
	float amplitude = p_vkEngine->waveAmplitude();
	p_FFT->GenerateHeightMap(m_waterParams.patchLength, m_waterParams.windSpeed, amplitude, m_waterParams.windDir);
}

